### PR TITLE
Invert the order of the flag and value in Option

### PR DESCRIPTION
**Pull request by danakj**
@davidben found that std's ordering is much smaller binary size than absl's in Chromuim.

### CODE REVIEW

**Comment by danakj** [comment]
cc: @davidben

**Comment by danakj** [comment]
Seems this is a clear win on ARM32 but not a clear win or barely worse elsewhere.

**Comment by davidben** [comment]
Yeah, we probably should figure out what's going on here first. 🙂

**Comment by danakj** [comment]
The difference seen here was actually a clang/llvm bug: https://github.com/llvm/llvm-project/issues/66709

We are better to keep the bool last so users can make use of the resulting tail padding.

**Comment by davidben** [comment]
Indeed after the Clang bug is worked around, bool last is smaller too.

**Pull request closed without merging**
