### PR TITLE
Replace deprecated endswith() with ends_with().

### PR DESCRIPTION
**Pull request by veluca93**

### CODE REVIEW

**Review by danakj — APPROVED** [review]
Can we avoid the reformatting changes? My clang-format is going to put them back on the next save. Maybe it would be nice to have a fixed clang-format version, it’s kind of a mess with how changes all the time. Anyway if it’s a pain it’s okay…

**Comment by veluca93** [comment]
> Can we avoid the reformatting changes? My clang-format is going to put them back on the next save. Maybe it would be nice to have a fixed clang-format version, it’s kind of a mess with how changes all the time. Anyway if it’s a pain it’s okay…

Just needed a commit -p :-)

**Comment by danakj** [comment]
> > Can we avoid the reformatting changes? My clang-format is going to put them back on the next save. Maybe it would be nice to have a fixed clang-format version, it’s kind of a mess with how changes all the time. Anyway if it’s a pain it’s okay…
> 
> Just needed a commit -p :-)

TIL about that flag :) Thanks!

**Comment by danakj** [comment]
Oh wow okay looks like clang 18 broke in a fun way:
```
Error while processing /home/runner/work/subspace/subspace/sus/num/i8_unittest.cc.
error: no such file or directory: '@sus/CMakeFiles/subspace_unittests.dir/mem/addressof_unittest.cc.o.modmap'
[2/99] /home/runner/work/subspace/subspace/sus/mem/addressof_unittest.cc
```

I will move it to 17 for now.

**Comment by danakj** [comment]
I will merge this, looks like it's not a clang-18 thing, maybe cmake.. but this CL is fine.

**Pull request merged**
