### PR TITLE
Add CMake option for building CIR.

### PR DESCRIPTION
**Pull request by dj2**
This CL adds an option into the cmake file to enable/disable the building of CIR. The default is `ON` but it will also honour the `SUBSPACE_NO_BUILD_CIR` environment variable to default off if set.

This allows doing `cmake -GNinja -DSUBPSACE_BUILD_CIR=OFF ../..` in order to configure cmake with the flag disabled (it would also allow setting the option in a downstream CMake configuration file).

### CODE REVIEW

**Comment by danakj** [comment]
Cool! Would you be open to just replacing the env var and using the new mechanism in the github workflow for clang-doc, and sticking something in the readme?

**Review by danakj — COMMENTED** [review]
Can we put the cmake module file under tools/cmake/?

**Comment by dj2** [comment]
Cmake files are moved to `tools/cmake`.

I'm happy to replace the env var in the github files but would prefer to do it as a second patch. That way, if I break CI during the transition it doesn't revert the cmake changes, just the CI files.

**Comment by danakj** [comment]
sure sgtm! thank you!

there's no trybots for the docs , but I don't think there's such thing as a revert at the moment 😂 , we'll just fix HEAD.

i'll submit when the trybots pass.

**Pull request merged**
